### ISSUE TITLE
Доработка класса Field

### ISSUE THREAD

**Issue by idma88** [DreamOn-DAL/PegSolitaire#18]
Метод `GetField` возвращает содержимое игрового поля, однако в настоящий момент нет возможности извне узнать его размер.

Необходимо добавить методы для получения ширины и высоты игрового поля

**Comment by AlexSnare** [comment]
Задача закрыта вместе с доработкой класса IGame

**Comment by AlexSnare** [comment]
6cb76c9fd9f179e454860a219a6429dc6c52a9d1
