### ISSUE TITLE
Разработка интерфейса игровой логики

### ISSUE THREAD

**Issue by idma88** [DreamOn-DAL/PegSolitaire#3]
* Поля:
  1. Игровое поле
  2. Список игроков
  3. Активный игрок

* Перечисления
  1. Игровой режим (одиночная/многопользовательская)

* Необходимые методы:
  1. Информация о игровом режиме
  2. Установить игровое поле
  3. Получить игровое поле
  4. Задать список игроков
  5. Получить список игроков
  6. Получить активного игрока (тот, которому предоставлен ход)
  7. Создание новой игры
  8. Проверка возможности указанного хода/последовательности ходов
  9. Выполнение хода
  10. Проверка конца игры

**Comment by AlexSnare** [comment]
Есть пару нюансов которые может помогут тебе определиться
1. Интерфейс должен определять все методы, которыми может пользоваться логика гуи
2. Я бы не делал тут поля, а предоставил управление классу логики
3. Я бы сделал его абстрактным и переопределил бы методы уже в CoreGame, тут возможно не совсем хорошо получается т.к много обязанностей ложится на CoreGame, но в целом выглядело бы логично

**Comment by idma88** [comment]
Исходя из последнего коммита я делаю вывод что ты не очень понял суть многих методов, которые надо реализовать. Поэтому держи комментарии по ним.

* Поля:
  1. Игровое поле
    > Экземпляр класса **Field**. Созданный экземпляр устанавливается извне через публичный метод (см. методы, п.2)
  2. Список игроков
    > Список экземпляров класса **Player**. Созданный список устанавливается извне через публичный метод (см. методы, п.4)
  3. Активный игрок
    > Порядковый номер в списке игоков; игрок, которому предоставлен ход.

* Методы:
  1. Информация о игровом режиме
    > Предоставляет информацию о игровом режиме(одиночная/многопользовательская)
  2. Установить игровое поле
    > Принимает экземпляр класс **Field**, который будет создан в классе бизнес-логики (ещё не реализовано)
  3. Получить игровое поле
    > Предоставляет экземпляр класс **Field**, который был установлен методом, описанным в п.2
  4. Задать список игроков
    > Принимает список экземпляров класса **Player**, который будет создан в классе бизнес-логики (ещё не реализовано)
  5. Получить список игроков
    > Предоставляет список экземпляров класса **Player**, который был установлен методом, описанным в п.4
  6. Получить активного игрока (тот, которому предоставлен ход)
  7. Создание новой игры
    > **Этот метод должен быть перегружен в классе наследнике**
    
    > Метод проверяет наличие установленного игрвого поля и списка игроков после чего "обнуляет" счёт игроков, устанавливает активного игрока (первый в списке).
  8. Проверка возможности указанного хода/последовательности ходов
    > Метод должен принимать координату ячейки с колышком и цепочку направлений ходов, и сообщать возможна ли такая последовательность ходов
  9. Выполнение хода
    > **Этот метод должен быть перегружен в классе наследнике**

    > Метод должен принимать координату ячейки с колышком и цепочку направлений ходов, проверять допустимость выполнения цепочки ходов и, в случае успеха, пересчитывать игровое поле, начислять очки активному игроку и передавать ход следующему игроку
  10. Проверка конца игры
    > Метод должен возвращать true, если есть возможность сделать хотя бы один ход

**Comment by AlexSnare** [comment]
30a13311f89688d9b33202ef494ba220f7aff286
