### ISSUE TITLE
Unit-тесты для интерфейса игровой логики

### ISSUE THREAD

**Issue by idma88** [DreamOn-DAL/PegSolitaire#9]
Протестировать общие методы:

  1. Информация о игровом режиме
  2. Создание новой игры
  3. Проверка возможности указанного хода/последовательности ходов
  4. Проверка конца игры
  5. Список игроков
  6. Активный пользователь (тот, которому предоставлен ход)

**Comment by AlexSnare** [comment]
30a13311f89688d9b33202ef494ba220f7aff286
